### ISSUE TITLE
Wrong  Package-Version for the sfpower-scratchorg-pool in documentation

### ISSUE THREAD

**Issue by Schuchie** [dxatscale/dxatscale-guide#31]
One package version on the following page for the package sfpower-scratch-pool:

https://docs.dxatscale.io/implementing-your-ci-cd/github/getting-started#e.-install-sfpowerscripts-scratch-org-pooling-unlocked-package-in-devhub

correct version as described from the last release: https://github.com/dxatscale/sfpower-scratchorg-pool#upgrading-from-110-1-to-200-1

**Comment by Caitlyn-Mills** [comment]
Thanks @Schuchie we will update this!

**Comment by henry88lay** [comment]
Hi @Caitlyn-Mills @Schuchie 

I have just updated the link on github, azure-devops and gitlab getting started pages.

Thank you for bringing this up.
